name: Deploy to Render

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'NOTES.md'
      - 'docs/**'
      - '**/*.md'
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.jpeg'
      - '**/*.gif'
      - '**/*.svg'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Render
        env:
          RENDER_TOKEN: ${{ secrets.RENDER_TOKEN }}
          RENDER_SERVICE_ID_BACKEND: ${{ secrets.RENDER_SERVICE_ID_BACKEND }}
          RENDER_SERVICE_ID_FRONTEND: ${{ secrets.RENDER_SERVICE_ID_FRONTEND }}
        run: |
          # Deploy backend first
          curl -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID_BACKEND/deploys" \
            -H "Authorization: Bearer $RENDER_TOKEN" \
            -H "Content-Type: application/json"
          
          # Wait a bit for backend to start
          sleep 30
          
          # Deploy frontend
          curl -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID_FRONTEND/deploys" \
            -H "Authorization: Bearer $RENDER_TOKEN" \
            -H "Content-Type: application/json"
