name: Terraform Deploy to Render

on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - 'apps/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/terraform-deploy.yml'

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Terraform Format Check
        run: terraform fmt -check -recursive terraform/

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          terraform plan \
            -var="render_token=$RENDER_API_KEY" \
            -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: terraform
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          terraform apply -auto-approve tfplan

      - name: Output URLs
        if: github.ref == 'refs/heads/main'
        working-directory: terraform
        run: |
          echo "Backend URL: $(terraform output -raw backend_url)"
          echo "Frontend URL: $(terraform output -raw frontend_url)"
          echo "GraphQL Playground: $(terraform output -raw graphql_playground_url)"
