name: Type Check

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - name: TypeScript - server
        run: pnpm --filter server typecheck
      - name: TypeScript - web
        run: pnpm --filter web typecheck
